services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bank-network

  hq-server:
    build: ./hq_server
    container_name: hq-central-server
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - bank-network

  branch-101:
    build: ./branch_node
    container_name: branch-node-101
    depends_on:
      - rabbitmq
    environment:
      - BRANCH_ID=101
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge
